<?php

/**
 * Public advertiser country landers (English URLs + English copy).
 * Catalog filters use primary country codes only (UK = uk, not gb).
 */
return [
    'germany' => [
        'slug' => 'guest-posts-germany',
        'codes' => ['de'],
        'market' => 'Germany',
        'keyword' => 'guest post cost germany',
        'kicker' => 'DACH publishers',
        'title' => 'Guest post cost in Germany',
        'meta_title' => 'Guest Post Cost in Germany — DACH Publishers, EUR',
        'meta_description' => 'See guest post cost in Germany on verified DACH publishers. EUR wallet, tracked live URLs, and a public sample of the catalog.',
        'subtitle' => 'Buy editorial placements on verified German sites. Pay in EUR, keep the live URL tracked, and browse the full catalog after you register.',
        'point_1_title' => 'German editorial sites',
        'point_1_body' => 'Listings are primary-Germany publishers — not a mixed “Europe” dump. Neighbouring DACH markets stay on their own filters after login.',
        'point_2_title' => 'EUR from the first quote',
        'point_2_body' => 'Advertiser prices include the placement fee. You fund a EUR wallet once and check out without currency surprises.',
        'point_3_title' => 'How to buy',
        'point_3_body' => 'Create an account, open the catalog, filter Germany, and send a brief. Delivery and the live URL stay on the order.',
        'teaser_title' => 'Sample German inventory',
        'teaser_subtitle' => 'Masked preview of live Germany listings. Register to see domains and the rest of the DACH catalog.',
        'blog_slugs' => [
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'guest-posting-in-the-uk-and-us-what-to-buy-and-what-to-skip',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'What does guest post cost in Germany usually look like?',
                'a' => 'There is no single rate. Public “from” prices on this page are the lowest advertiser price on verified Germany listings right now. Metrics, niche, and homepage extras move the quote.',
            ],
            [
                'q' => 'Do you cover Austria and Switzerland as well as Germany?',
                'a' => 'This lander previews primary-Germany sites. After login you can also filter AT and CH. The wallet and order flow stay the same.',
            ],
            [
                'q' => 'Are the prices on this page the publisher list price?',
                'a' => 'No. You see the advertiser checkout price. Publisher domains stay masked until you register.',
            ],
            [
                'q' => 'How do I buy a German guest post?',
                'a' => 'Register, add EUR to the wallet, pick a Germany listing, and send the brief. The publisher delivers a live URL you can approve or send back.',
            ],
        ],
    ],
    'uk' => [
        'slug' => 'guest-posts-uk',
        'codes' => ['uk'],
        'market' => 'United Kingdom',
        'keyword' => 'guest posts uk',
        'kicker' => 'UK publishers',
        'title' => 'Guest posts in the UK',
        'meta_title' => 'Guest Posts in the UK — Publishers, Prices, What to Buy',
        'meta_description' => 'Buy guest posts in the UK on verified publishers. EUR wallet, tracked delivery, and a public sample of UK inventory.',
        'subtitle' => 'UK is its own English market — not a bundle with the US. Filter UK publishers, pay in EUR, and track the live URL.',
        'point_1_title' => 'UK-primary listings',
        'point_1_body' => 'These teasers are sites whose primary country is the United Kingdom. US and other English markets stay on their own filters.',
        'point_2_title' => 'EUR checkout',
        'point_2_body' => 'Quotes and the wallet are in EUR even when the publisher is British. New advertisers still get the welcome credit on first orders.',
        'point_3_title' => 'What to skip',
        'point_3_body' => 'Treat “English” as a language, not a country. If you need UK readers or a UK brand SERP, filter UK — do not buy a generic English site and hope.',
        'teaser_title' => 'Sample UK inventory',
        'teaser_subtitle' => 'Masked preview of live UK listings. Register to open domains and the rest of the catalog.',
        'blog_slugs' => [
            'guest-posting-in-the-uk-and-us-what-to-buy-and-what-to-skip',
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'Are UK guest posts the same as US guest posts?',
                'a' => 'No. Audience, news cycle, and often the TLD differ. Use this page for United Kingdom inventory; keep US as a separate filter after login.',
            ],
            [
                'q' => 'Why is the country code UK and not GB?',
                'a' => 'The catalog stores the United Kingdom as uk. That is the code you will see on listings and in filters.',
            ],
            [
                'q' => 'Can I pay in pounds?',
                'a' => 'Checkout is EUR. Convert once when you fund the wallet; order prices stay in euro.',
            ],
            [
                'q' => 'How do I place a UK guest post?',
                'a' => 'Register, fund the wallet, filter United Kingdom, and send a brief. The live URL comes back on the order for review.',
            ],
        ],
    ],
    'italy' => [
        'slug' => 'guest-posts-italy',
        'codes' => ['it'],
        'market' => 'Italy',
        'keyword' => 'comprare guest post',
        'kicker' => 'Italian publishers',
        'title' => 'Guest posts in Italy',
        'meta_title' => 'Guest Posts in Italy — Comprare Guest Post in EUR',
        'meta_description' => 'Comprare guest post on verified Italian publishers. EUR wallet, tracked live URLs, and a public sample of Italy inventory.',
        'subtitle' => 'Editorial placements on primary-Italy sites. Comprare guest post with a EUR wallet and a tracked live URL — not a PDF invoice from a broker.',
        'point_1_title' => 'Italy-primary publishers',
        'point_1_body' => 'Teasers are sites whose primary country is Italy. Language is usually Italian; confirm the listing language before you brief.',
        'point_2_title' => 'EUR, not a hidden markup list',
        'point_2_body' => 'The “from” price is the advertiser checkout amount. Fund once and buy as many Italian placements as the brief needs.',
        'point_3_title' => 'How to buy',
        'point_3_body' => 'Register, open the catalog, filter Italy, and send anchors and the destination URL. The publisher returns the live article for approval.',
        'teaser_title' => 'Sample Italian inventory',
        'teaser_subtitle' => 'Masked preview of live Italy listings. Register to see domains and place the order.',
        'blog_slugs' => [
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'how-to-choose-a-publisher-site-dr-da-traffic-niche',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'Posso comprare guest post in Italia da questo marketplace?',
                'a' => 'Yes. This page is the English lander for Italy inventory. After you register, filter country Italy and check out in EUR.',
            ],
            [
                'q' => 'Is the article written in Italian?',
                'a' => 'Most Italy-primary sites publish in Italian. The listing language is on the catalog row — match the brief to that language.',
            ],
            [
                'q' => 'Do you show the publisher domain here?',
                'a' => 'Not on this public page. Domains stay masked until you create an account.',
            ],
            [
                'q' => 'What happens after the post goes live?',
                'a' => 'The live URL is attached to the order. You can approve it or request changes from the same thread.',
            ],
        ],
    ],
    'spain' => [
        'slug' => 'guest-posts-spain',
        'codes' => ['es'],
        'market' => 'Spain',
        'keyword' => 'guest post comprar',
        'kicker' => 'Spanish publishers',
        'title' => 'Guest posts in Spain',
        'meta_title' => 'Guest Posts in Spain — Guest Post Comprar in EUR',
        'meta_description' => 'Guest post comprar on verified Spanish publishers. EUR wallet, tracked live URLs, and a public sample of Spain inventory.',
        'subtitle' => 'Primary-Spain publishers for teams who need to guest post comprar with a clear EUR price and a live URL on the order.',
        'point_1_title' => 'Spain-primary listings',
        'point_1_body' => 'These teasers are sites whose primary country is Spain. Latin American inventory is a different filter after login.',
        'point_2_title' => 'EUR wallet',
        'point_2_body' => 'Checkout is in euro. Fund the wallet once, then buy Spanish placements without a new invoice each time.',
        'point_3_title' => 'Language fit',
        'point_3_body' => 'Confirm Spanish (or Catalan / regional) on the listing before you write the brief. Country and language are separate filters.',
        'teaser_title' => 'Sample Spanish inventory',
        'teaser_subtitle' => 'Masked preview of live Spain listings. Register to see domains and buy.',
        'blog_slugs' => [
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'how-to-choose-a-publisher-site-dr-da-traffic-niche',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'Puedo hacer guest post comprar en sitios de España?',
                'a' => 'Yes. Register, filter country Spain, and check out in EUR. This page is the public English lander for that inventory.',
            ],
            [
                'q' => 'Does Spain include Latin America?',
                'a' => 'No. This preview is primary-Spain only. Mexico and other LATAM markets have their own country filters after login.',
            ],
            [
                'q' => 'Are prices the publisher’s list price?',
                'a' => 'You see the advertiser checkout price. Publisher domains stay masked on this page.',
            ],
            [
                'q' => 'How is the live URL delivered?',
                'a' => 'The publisher submits it on the order. You review it there — no side-channel Google Doc.',
            ],
        ],
    ],
    'france' => [
        'slug' => 'guest-posts-france',
        'codes' => ['fr'],
        'market' => 'France',
        'keyword' => 'acheter guest post',
        'kicker' => 'French publishers',
        'title' => 'Guest posts in France',
        'meta_title' => 'Guest Posts in France — Acheter Guest Post in EUR',
        'meta_description' => 'Acheter guest post on verified French publishers. EUR wallet, tracked live URLs, and a public sample of France inventory.',
        'subtitle' => 'Primary-France publishers. Acheter guest post with a EUR wallet and a tracked live URL on the order.',
        'point_1_title' => 'France-primary sites',
        'point_1_body' => 'Teasers are listings whose primary country is France. Belgian or Swiss French sites are not mixed in here.',
        'point_2_title' => 'EUR native',
        'point_2_body' => 'Prices and the wallet are already in euro. No extra FX step for a French campaign.',
        'point_3_title' => 'How to buy',
        'point_3_body' => 'Register, filter France, send the brief in the listing language, and approve the live URL on the order.',
        'teaser_title' => 'Sample French inventory',
        'teaser_subtitle' => 'Masked preview of live France listings. Register to open domains and check out.',
        'blog_slugs' => [
            'acheter-des-guest-posts-sur-seolinkbuildings-guide-annonceur',
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'Comment acheter guest post sur des sites français?',
                'a' => 'Create an account, filter country France, fund the EUR wallet, and send the brief. This page is the public English lander for that catalog slice.',
            ],
            [
                'q' => 'Is the article in French?',
                'a' => 'Most France-primary sites publish in French. Check the listing language before you write.',
            ],
            [
                'q' => 'Do you include Belgium or Switzerland?',
                'a' => 'Not on this lander. Those countries have their own primary-country filters after login.',
            ],
            [
                'q' => 'What if the live link is removed later?',
                'a' => 'Use the order thread. The marketplace tracks the live URL so a removal is not a lost email.',
            ],
        ],
    ],
    'netherlands' => [
        'slug' => 'guest-posts-netherlands',
        'codes' => ['nl'],
        'market' => 'Netherlands',
        'keyword' => 'guest post kopen',
        'kicker' => 'Benelux publishers',
        'title' => 'Guest posts in the Netherlands',
        'meta_title' => 'Guest Posts in the Netherlands — Guest Post Kopen in EUR',
        'meta_description' => 'Guest post kopen on verified Dutch publishers. EUR wallet, tracked live URLs, and a public sample of Netherlands inventory.',
        'subtitle' => 'Primary-Netherlands publishers for teams who want to guest post kopen with a EUR price and a live URL on the order.',
        'point_1_title' => 'Netherlands-primary listings',
        'point_1_body' => 'This preview is NL-primary sites. Belgium and Luxembourg stay on their own filters after login — useful if you need the rest of Benelux.',
        'point_2_title' => 'EUR wallet',
        'point_2_body' => 'Dutch campaigns check out in euro. Fund once and buy placements without a new invoice per site.',
        'point_3_title' => 'Language',
        'point_3_body' => 'Many NL sites publish in Dutch; some accept English. Match the brief to the listing language.',
        'teaser_title' => 'Sample Dutch inventory',
        'teaser_subtitle' => 'Masked preview of live Netherlands listings. Register to see domains and buy.',
        'blog_slugs' => [
            'gastposts-kopen-op-seolinkbuildings-adverteerdersgids',
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'Kan ik hier guest post kopen op Nederlandse sites?',
                'a' => 'Yes. Register, filter country Netherlands, and check out in EUR. This English page is the public lander for that slice.',
            ],
            [
                'q' => 'Is Belgium included?',
                'a' => 'Not in this preview. Filter Belgium after login if you need BE-primary publishers.',
            ],
            [
                'q' => 'Are domains public on this page?',
                'a' => 'No. Names are shown, hosts are masked, until you create an account.',
            ],
            [
                'q' => 'How does delivery work?',
                'a' => 'The publisher submits the live URL on the order. You approve it or request changes there.',
            ],
        ],
    ],
];
