<?php

/**
 * Public advertiser country landers (English URLs + English copy).
 * Catalog filters use primary country codes only (UK = uk, not gb).
 */
return [
    'germany' => [
        'slug' => 'guest-posts-germany',
        'codes' => ['de'],
        'market' => 'Germany',
        'keyword' => 'guest post cost germany',
        'kicker' => 'DACH publishers',
        'title' => 'Guest post cost in Germany',
        'meta_title' => 'Guest Post Cost in Germany — DACH Publishers, EUR',
        'meta_description' => 'See guest post cost in Germany on verified DACH publishers. EUR wallet, tracked live URLs, and a public sample of the catalog.',
        'subtitle' => 'Buy editorial placements on verified German sites. Pay in EUR, keep the live URL tracked, and browse the full catalog after you register.',
        'point_1_title' => 'German editorial sites',
        'point_1_body' => 'Listings are primary-Germany publishers — not a mixed “Europe” dump. Neighbouring DACH markets stay on their own filters after login.',
        'point_2_title' => 'EUR from the first quote',
        'point_2_body' => 'Advertiser prices include the placement fee. You fund a EUR wallet once and check out without currency surprises.',
        'point_3_title' => 'How to buy',
        'point_3_body' => 'Create an account, open the catalog, filter Germany, and send a brief. Delivery and the live URL stay on the order.',
        'teaser_title' => 'Sample German inventory',
        'teaser_subtitle' => 'Masked preview of live Germany listings. Register to see domains and the rest of the DACH catalog.',
        'blog_slugs' => [
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'guest-posting-in-the-uk-and-us-what-to-buy-and-what-to-skip',
            'wallet-escrow-and-refunds-explained',
        ],
        'native_url' => '/de/gastbeitrag-kaufen',
        'native_label' => 'Gastbeitrag kaufen auf Deutsch',
        'faqs' => [
            [
                'q' => 'What does guest post cost in Germany usually look like?',
                'a' => 'There is no single rate. Public “from” prices on this page are the lowest advertiser price on verified Germany listings right now. Metrics, niche, and homepage extras move the quote.',
            ],
            [
                'q' => 'Do you cover Austria and Switzerland as well as Germany?',
                'a' => 'This lander previews primary-Germany sites. After login you can also filter AT and CH. The wallet and order flow stay the same.',
            ],
            [
                'q' => 'Are the prices on this page the publisher list price?',
                'a' => 'No. You see the advertiser checkout price. Publisher domains stay masked until you register.',
            ],
            [
                'q' => 'How do I buy a German guest post?',
                'a' => 'Register, add EUR to the wallet, pick a Germany listing, and send the brief. The publisher delivers a live URL you can approve or send back.',
            ],
        ],
    ],
    'uk' => [
        'slug' => 'guest-posts-uk',
        'codes' => ['uk'],
        'market' => 'United Kingdom',
        'keyword' => 'guest posts uk',
        'kicker' => 'UK publishers',
        'title' => 'Guest posts in the UK',
        'meta_title' => 'Guest Posts in the UK — Publishers, Prices, What to Buy',
        'meta_description' => 'Buy guest posts in the UK on verified publishers. EUR wallet, tracked delivery, and a public sample of UK inventory.',
        'subtitle' => 'UK is its own English market — not a bundle with the US. Filter UK publishers, pay in EUR, and track the live URL.',
        'point_1_title' => 'UK-primary listings',
        'point_1_body' => 'These teasers are sites whose primary country is the United Kingdom. US and other English markets stay on their own filters.',
        'point_2_title' => 'EUR checkout',
        'point_2_body' => 'Quotes and the wallet are in EUR even when the publisher is British. New advertisers still get the welcome credit on first orders.',
        'point_3_title' => 'What to skip',
        'point_3_body' => 'Treat “English” as a language, not a country. If you need UK readers or a UK brand SERP, filter UK — do not buy a generic English site and hope.',
        'teaser_title' => 'Sample UK inventory',
        'teaser_subtitle' => 'Masked preview of live UK listings. Register to open domains and the rest of the catalog.',
        'blog_slugs' => [
            'guest-posting-in-the-uk-and-us-what-to-buy-and-what-to-skip',
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'Are UK guest posts the same as US guest posts?',
                'a' => 'No. Audience, news cycle, and often the TLD differ. Use this page for United Kingdom inventory; keep US as a separate filter after login.',
            ],
            [
                'q' => 'Why is the country code UK and not GB?',
                'a' => 'The catalog stores the United Kingdom as uk. That is the code you will see on listings and in filters.',
            ],
            [
                'q' => 'Can I pay in pounds?',
                'a' => 'Checkout is EUR. Convert once when you fund the wallet; order prices stay in euro.',
            ],
            [
                'q' => 'How do I place a UK guest post?',
                'a' => 'Register, fund the wallet, filter United Kingdom, and send a brief. The live URL comes back on the order for review.',
            ],
        ],
    ],
    'italy' => [
        'slug' => 'guest-posts-italy',
        'codes' => ['it'],
        'market' => 'Italy',
        'keyword' => 'comprare guest post',
        'kicker' => 'Italian publishers',
        'title' => 'Guest posts in Italy',
        'meta_title' => 'Guest Posts in Italy — Verified Publishers, EUR',
        'meta_description' => 'Buy guest posts on verified Italian publishers. EUR wallet, tracked live URLs, and a public sample of Italy inventory.',
        'subtitle' => 'Editorial placements on primary-Italy sites. Pay in EUR and keep the live URL on the order — not a PDF invoice from a broker.',
        'point_1_title' => 'Italy-primary publishers',
        'point_1_body' => 'Teasers are sites whose primary country is Italy. Language is usually Italian; confirm the listing language before you brief.',
        'point_2_title' => 'EUR, not a hidden markup list',
        'point_2_body' => 'The “from” price is the advertiser checkout amount. Fund once and buy as many Italian placements as the brief needs.',
        'point_3_title' => 'How to buy',
        'point_3_body' => 'Register, open the catalog, filter Italy, and send anchors and the destination URL. The publisher returns the live article for approval.',
        'teaser_title' => 'Sample Italian inventory',
        'teaser_subtitle' => 'Masked preview of live Italy listings. Register to see domains and place the order.',
        'blog_slugs' => [
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'how-to-choose-a-publisher-site-dr-da-traffic-niche',
            'wallet-escrow-and-refunds-explained',
        ],
        'native_url' => '/it/comprare-guest-post',
        'native_label' => 'Acquistare guest post in italiano',
        'faqs' => [
            [
                'q' => 'Posso comprare guest post in Italia da questo marketplace?',
                'a' => 'Yes. This English page is the public lander for Italy inventory. The Italian conversion page is /it/comprare-guest-post. After you register, filter country Italy and check out in EUR.',
            ],
            [
                'q' => 'Is the article written in Italian?',
                'a' => 'Most Italy-primary sites publish in Italian. The listing language is on the catalog row — match the brief to that language.',
            ],
            [
                'q' => 'Do you show the publisher domain here?',
                'a' => 'Not on this public page. Domains stay masked until you create an account.',
            ],
            [
                'q' => 'What happens after the post goes live?',
                'a' => 'The live URL is attached to the order. You can approve it or request changes from the same thread.',
            ],
        ],
    ],
    'spain' => [
        'slug' => 'guest-posts-spain',
        'codes' => ['es'],
        'market' => 'Spain',
        'keyword' => 'guest post comprar',
        'kicker' => 'Spanish publishers',
        'title' => 'Guest posts in Spain',
        'meta_title' => 'Guest Posts in Spain — Verified Publishers, EUR',
        'meta_description' => 'Buy guest posts in Spain on verified publishers. EUR wallet, tracked live URLs, and a public sample of Spain inventory.',
        'subtitle' => 'Primary-Spain publishers with a clear EUR price and a live URL on the order.',
        'point_1_title' => 'Spain-primary listings',
        'point_1_body' => 'These teasers are sites whose primary country is Spain. Latin American inventory is a different filter after login.',
        'point_2_title' => 'EUR wallet',
        'point_2_body' => 'Checkout is in euro. Fund the wallet once, then buy Spanish placements without a new invoice each time.',
        'point_3_title' => 'Language fit',
        'point_3_body' => 'Confirm Spanish (or Catalan / regional) on the listing before you write the brief. Country and language are separate filters.',
        'teaser_title' => 'Sample Spanish inventory',
        'teaser_subtitle' => 'Masked preview of live Spain listings. Register to see domains and buy.',
        'blog_slugs' => [
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'how-to-choose-a-publisher-site-dr-da-traffic-niche',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => '¿Puedo comprar guest posts en sitios de España?',
                'a' => 'Yes. Register, filter country Spain, and check out in EUR. This English page is the public lander for that inventory.',
            ],
            [
                'q' => 'Does Spain include Latin America?',
                'a' => 'No. This preview is primary-Spain only. Mexico and other LATAM markets have their own country filters after login.',
            ],
            [
                'q' => 'Are prices the publisher’s list price?',
                'a' => 'You see the advertiser checkout price. Publisher domains stay masked on this page.',
            ],
            [
                'q' => 'How is the live URL delivered?',
                'a' => 'The publisher submits it on the order. You review it there — no side-channel Google Doc.',
            ],
        ],
    ],
    'portugal' => [
        'slug' => 'guest-posts-portugal',
        'codes' => ['pt'],
        'market' => 'Portugal',
        'keyword' => 'comprar guest post',
        'kicker' => 'Portuguese publishers',
        'title' => 'Guest posts in Portugal',
        'meta_title' => 'Guest Posts in Portugal — Verified Publishers, EUR',
        'meta_description' => 'Buy guest posts in Portugal on verified publishers. EUR wallet, tracked live URLs, and a public sample of Portugal inventory.',
        'subtitle' => 'Primary-Portugal publishers with a clear EUR price and a live URL on the order.',
        'point_1_title' => 'Portugal-primary listings',
        'point_1_body' => 'These teasers are sites whose primary country is Portugal. Brazil and other Portuguese-speaking markets are a different filter after login.',
        'point_2_title' => 'EUR wallet',
        'point_2_body' => 'Checkout is in euro. Fund the wallet once, then buy Portuguese placements without a new invoice each time.',
        'point_3_title' => 'Language fit',
        'point_3_body' => 'Confirm European Portuguese on the listing before you write the brief. Country and language are separate filters.',
        'teaser_title' => 'Sample Portuguese inventory',
        'teaser_subtitle' => 'Masked preview of live Portugal listings. Register to see domains and buy.',
        'native_url' => '/pt/comprar-guest-post',
        'native_label' => 'Comprar guest post em português',
        'blog_slugs' => [
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'how-to-choose-a-publisher-site-dr-da-traffic-niche',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'Can I buy guest posts on Portuguese sites?',
                'a' => 'Yes. Register, filter country Portugal, and check out in EUR. The Portuguese page is /pt/comprar-guest-post.',
            ],
            [
                'q' => 'Does Portugal include Brazil?',
                'a' => 'No. This preview is primary-Portugal only. Brazil has its own country filter after login.',
            ],
            [
                'q' => 'Are prices the publisher’s list price?',
                'a' => 'You see the advertiser checkout price. Publisher domains stay masked on this page.',
            ],
            [
                'q' => 'How is the live URL delivered?',
                'a' => 'The publisher submits it on the order. You review it there.',
            ],
        ],
    ],
    'france' => [
        'slug' => 'guest-posts-france',
        'codes' => ['fr'],
        'market' => 'France',
        'keyword' => 'acheter guest post',
        'kicker' => 'French publishers',
        'title' => 'Guest posts in France',
        'meta_title' => 'Acheter Guest Post in France — Verified Publishers, EUR',
        'meta_description' => 'Buy guest posts on verified French publishers. EUR wallet, tracked live URLs, and a public sample of France inventory.',
        'subtitle' => 'Primary-France publishers. Pay in EUR and keep the live URL on the order.',
        'point_1_title' => 'France-primary sites',
        'point_1_body' => 'Teasers are listings whose primary country is France. Belgian or Swiss French sites are not mixed in here.',
        'point_2_title' => 'EUR native',
        'point_2_body' => 'Prices and the wallet are already in euro. No extra FX step for a French campaign.',
        'point_3_title' => 'How to buy',
        'point_3_body' => 'Register, filter France, send the brief in the listing language, and approve the live URL on the order.',
        'teaser_title' => 'Sample French inventory',
        'teaser_subtitle' => 'Masked preview of live France listings. Register to open domains and check out.',
        'blog_slugs' => [
            'acheter-des-guest-posts-sur-seolinkbuildings-guide-annonceur',
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'Comment acheter un guest post sur des sites français ?',
                'a' => 'Create an account, filter country France, fund the EUR wallet, and send the brief. This English page is the public lander for that catalog slice.',
            ],
            [
                'q' => 'Is the article in French?',
                'a' => 'Most France-primary sites publish in French. Check the listing language before you write.',
            ],
            [
                'q' => 'Do you include Belgium or Switzerland?',
                'a' => 'Not on this lander. Those countries have their own primary-country filters after login.',
            ],
            [
                'q' => 'What if the live link is removed later?',
                'a' => 'Use the order thread. The marketplace tracks the live URL so a removal is not a lost email.',
            ],
        ],
    ],
    'netherlands' => [
        'slug' => 'guest-posts-netherlands',
        'codes' => ['nl'],
        'market' => 'Netherlands',
        'keyword' => 'guest post kopen',
        'kicker' => 'Benelux publishers',
        'title' => 'Guest posts in the Netherlands',
        'meta_title' => 'Guest Post Kopen in the Netherlands — Verified Publishers, EUR',
        'meta_description' => 'Buy guest posts on verified Dutch publishers. EUR wallet, tracked live URLs, and a public sample of Netherlands inventory.',
        'subtitle' => 'Primary-Netherlands publishers with a EUR price and a live URL on the order.',
        'point_1_title' => 'Netherlands-primary listings',
        'point_1_body' => 'This preview is NL-primary sites. Belgium and Luxembourg stay on their own filters after login — useful if you need the rest of Benelux.',
        'point_2_title' => 'EUR wallet',
        'point_2_body' => 'Dutch campaigns check out in euro. Fund once and buy placements without a new invoice per site.',
        'point_3_title' => 'Language',
        'point_3_body' => 'Many NL sites publish in Dutch; some accept English. Match the brief to the listing language.',
        'teaser_title' => 'Sample Dutch inventory',
        'teaser_subtitle' => 'Masked preview of live Netherlands listings. Register to see domains and buy.',
        'blog_slugs' => [
            'gastposts-kopen-op-seolinkbuildings-adverteerdersgids',
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'Kan ik hier guest post kopen op Nederlandse sites?',
                'a' => 'Yes. Register, filter country Netherlands, and check out in EUR. This English page is the public lander for that slice.',
            ],
            [
                'q' => 'Is Belgium included?',
                'a' => 'Not in this preview. Filter Belgium after login if you need BE-primary publishers.',
            ],
            [
                'q' => 'Are domains public on this page?',
                'a' => 'No. Names are shown, hosts are masked, until you create an account.',
            ],
            [
                'q' => 'How does delivery work?',
                'a' => 'The publisher submits the live URL on the order. You approve it or request changes there.',
            ],
        ],
    ],
    'switzerland' => [
        'slug' => 'guest-posts-switzerland',
        'codes' => ['ch'],
        'market' => 'Switzerland',
        'keyword' => 'guest posts switzerland',
        'kicker' => 'Swiss publishers',
        'title' => 'Guest posts in Switzerland',
        'meta_title' => 'Guest Posts in Switzerland — CH Publishers, EUR',
        'meta_description' => 'Buy guest posts on verified Swiss publishers. EUR wallet, tracked live URLs, and a public sample of Switzerland inventory.',
        'subtitle' => 'Primary-Switzerland publishers. This lander is the German-Switzerland market — not a mixed DACH dump.',
        'point_1_title' => 'Switzerland-primary listings',
        'point_1_body' => 'Teasers are sites whose primary country is Switzerland. Germany and Austria stay on their own landers and catalog filters.',
        'point_2_title' => 'EUR checkout',
        'point_2_body' => 'Quotes and the wallet are in euro. Fund once, then buy Swiss placements without a new invoice per site.',
        'point_3_title' => 'Language',
        'point_3_body' => 'Most CH-primary sites here publish in German. Confirm French or Italian on the listing before you brief if you need those languages.',
        'teaser_title' => 'Sample Swiss inventory',
        'teaser_subtitle' => 'Masked preview of live Switzerland listings. Register to see domains and buy.',
        'blog_slugs' => [
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'how-to-choose-a-publisher-site-dr-da-traffic-niche',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'Is this the same as the Germany lander?',
                'a' => 'No. This preview is primary-Switzerland only. Filter Germany or Austria after login if you need those markets.',
            ],
            [
                'q' => 'Do you cover French-speaking Switzerland?',
                'a' => 'Country is Switzerland; language is a separate catalog filter. Check the listing language before you write the brief.',
            ],
            [
                'q' => 'Are domains public here?',
                'a' => 'No. Hosts stay masked until you create an account.',
            ],
            [
                'q' => 'How do I buy a Swiss guest post?',
                'a' => 'Register, fund the EUR wallet, filter Switzerland, and send the brief. The live URL comes back on the order.',
            ],
        ],
    ],
    'austria' => [
        'slug' => 'guest-posts-austria',
        'codes' => ['at'],
        'market' => 'Austria',
        'keyword' => 'guest posts austria',
        'kicker' => 'Austrian publishers',
        'title' => 'Guest posts in Austria',
        'meta_title' => 'Guest Posts in Austria — AT Publishers, EUR',
        'meta_description' => 'Buy guest posts on verified Austrian publishers. EUR wallet, tracked live URLs, and a public sample of Austria inventory.',
        'subtitle' => 'Primary-Austria publishers with a EUR price and a live URL on the order.',
        'point_1_title' => 'Austria-primary listings',
        'point_1_body' => 'These teasers are AT-primary sites — not Germany and not a generic DACH bundle.',
        'point_2_title' => 'EUR wallet',
        'point_2_body' => 'Checkout is in euro. Fund once and buy Austrian placements without currency surprises.',
        'point_3_title' => 'How to buy',
        'point_3_body' => 'Register, filter Austria, send a German-language brief unless the listing says otherwise, and approve the live URL on the order.',
        'teaser_title' => 'Sample Austrian inventory',
        'teaser_subtitle' => 'Masked preview of live Austria listings. Register to see domains and place the order.',
        'native_url' => '/at/gastbeitrag-kaufen',
        'native_label' => 'Gastbeitrag kaufen auf Deutsch (Österreich)',
        'blog_slugs' => [
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'how-to-choose-a-publisher-site-dr-da-traffic-niche',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'Is Austria mixed into the Germany catalog?',
                'a' => 'Not on this page. Primary country is Austria. Germany and Switzerland have their own landers.',
            ],
            [
                'q' => 'What language should the article be?',
                'a' => 'Most AT-primary sites publish in German. Match the brief to the listing language.',
            ],
            [
                'q' => 'Do you show the publisher domain here?',
                'a' => 'Not on this public page. Domains stay masked until you register.',
            ],
            [
                'q' => 'How is delivery tracked?',
                'a' => 'The publisher submits the live URL on the order. You approve it or request changes there.',
            ],
        ],
    ],
    'romania' => [
        'slug' => 'guest-posts-romania',
        'codes' => ['ro'],
        'market' => 'Romania',
        'keyword' => 'guest posts romania',
        'kicker' => 'Romanian publishers',
        'title' => 'Guest posts in Romania',
        'meta_title' => 'Guest Posts in Romania — RO Publishers, EUR',
        'meta_description' => 'Buy guest posts on verified Romanian publishers. EUR wallet, tracked live URLs, and a public sample of Romania inventory.',
        'subtitle' => 'Primary-Romania publishers. Pay in EUR and keep the live URL on the order.',
        'point_1_title' => 'Romania-primary listings',
        'point_1_body' => 'Teasers are sites whose primary country is Romania. Neighbouring markets stay on their own filters after login.',
        'point_2_title' => 'EUR from the first quote',
        'point_2_body' => 'Advertiser prices include the placement fee. Fund a EUR wallet once and check out without a new invoice per site.',
        'point_3_title' => 'Language',
        'point_3_body' => 'Most RO-primary sites publish in Romanian. Confirm the listing language before you brief.',
        'teaser_title' => 'Sample Romanian inventory',
        'teaser_subtitle' => 'Masked preview of live Romania listings. Register to see domains and buy.',
        'blog_slugs' => [
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'how-to-choose-a-publisher-site-dr-da-traffic-niche',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'Can I buy Romanian guest posts here?',
                'a' => 'Yes. Register, filter country Romania, and check out in EUR. This English page is the public lander for that slice.',
            ],
            [
                'q' => 'Is the article written in Romanian?',
                'a' => 'Usually yes. The listing language is on the catalog row — match the brief to that language.',
            ],
            [
                'q' => 'Are domains public on this page?',
                'a' => 'No. Names are shown, hosts are masked, until you create an account.',
            ],
            [
                'q' => 'How does delivery work?',
                'a' => 'The publisher submits the live URL on the order. You approve it or request changes there.',
            ],
        ],
    ],
    'greece' => [
        'slug' => 'guest-posts-greece',
        'codes' => ['gr'],
        'market' => 'Greece',
        'keyword' => 'guest posts greece',
        'kicker' => 'Greek publishers',
        'title' => 'Guest posts in Greece',
        'meta_title' => 'Guest Posts in Greece — GR Publishers, EUR',
        'meta_description' => 'Buy guest posts on verified Greek publishers. EUR wallet, tracked live URLs, and a public sample of Greece inventory.',
        'subtitle' => 'Primary-Greece publishers with a EUR price and a live URL on the order.',
        'point_1_title' => 'Greece-primary listings',
        'point_1_body' => 'This preview is GR-primary sites. Cyprus and other Greek-language markets stay on their own filters after login.',
        'point_2_title' => 'EUR wallet',
        'point_2_body' => 'Checkout is in euro. Fund once and buy Greek placements without currency surprises.',
        'point_3_title' => 'Language',
        'point_3_body' => 'Most GR-primary sites publish in Greek. Match the brief to the listing language.',
        'teaser_title' => 'Sample Greek inventory',
        'teaser_subtitle' => 'Masked preview of live Greece listings. Register to see domains and buy.',
        'blog_slugs' => [
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'how-to-choose-a-publisher-site-dr-da-traffic-niche',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'Can I buy guest posts on Greek sites here?',
                'a' => 'Yes. Register, filter country Greece, and check out in EUR.',
            ],
            [
                'q' => 'Is Cyprus included?',
                'a' => 'Not in this preview. Filter Cyprus after login if you need CY-primary publishers.',
            ],
            [
                'q' => 'Are prices the publisher list price?',
                'a' => 'You see the advertiser checkout price. Publisher domains stay masked on this page.',
            ],
            [
                'q' => 'How is the live URL delivered?',
                'a' => 'The publisher submits it on the order. You review it there.',
            ],
        ],
    ],
    'denmark' => [
        'slug' => 'guest-posts-denmark',
        'codes' => ['dk'],
        'market' => 'Denmark',
        'keyword' => 'guest posts denmark',
        'kicker' => 'Danish publishers',
        'title' => 'Guest posts in Denmark',
        'meta_title' => 'Guest Posts in Denmark — DK Publishers, EUR',
        'meta_description' => 'Buy guest posts on verified Danish publishers. EUR wallet, tracked live URLs, and a public sample of Denmark inventory.',
        'subtitle' => 'Primary-Denmark publishers. Pay in EUR and keep the live URL on the order.',
        'point_1_title' => 'Denmark-primary listings',
        'point_1_body' => 'Teasers are DK-primary sites. Sweden, Norway, and Finland stay on their own Nordic landers and filters.',
        'point_2_title' => 'EUR checkout',
        'point_2_body' => 'Quotes and the wallet are in euro even when the publisher is Danish.',
        'point_3_title' => 'How to buy',
        'point_3_body' => 'Register, filter Denmark, send the brief in the listing language, and approve the live URL on the order.',
        'teaser_title' => 'Sample Danish inventory',
        'teaser_subtitle' => 'Masked preview of live Denmark listings. Register to open domains and check out.',
        'blog_slugs' => [
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'how-to-choose-a-publisher-site-dr-da-traffic-niche',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'Is this a mixed Nordic catalog?',
                'a' => 'No. This page is primary-Denmark only. Sweden and Norway have their own landers.',
            ],
            [
                'q' => 'Should the article be in Danish?',
                'a' => 'Most DK-primary sites publish in Danish. Check the listing language before you write.',
            ],
            [
                'q' => 'Do you show domains here?',
                'a' => 'No. Hosts stay masked until you register.',
            ],
            [
                'q' => 'How do I place the order?',
                'a' => 'Create an account, fund the EUR wallet, filter Denmark, and send the brief.',
            ],
        ],
    ],
    'sweden' => [
        'slug' => 'guest-posts-sweden',
        'codes' => ['se'],
        'market' => 'Sweden',
        'keyword' => 'guest posts sweden',
        'kicker' => 'Swedish publishers',
        'title' => 'Guest posts in Sweden',
        'meta_title' => 'Guest Posts in Sweden — SE Publishers, EUR',
        'meta_description' => 'Buy guest posts on verified Swedish publishers. EUR wallet, tracked live URLs, and a public sample of Sweden inventory.',
        'subtitle' => 'Primary-Sweden publishers with a EUR price and a live URL on the order.',
        'point_1_title' => 'Sweden-primary listings',
        'point_1_body' => 'This preview is SE-primary sites — not a bundled Nordic dump.',
        'point_2_title' => 'EUR wallet',
        'point_2_body' => 'Checkout is in euro. Fund once and buy Swedish placements without a new invoice per site.',
        'point_3_title' => 'Language',
        'point_3_body' => 'Most SE-primary sites publish in Swedish. Match the brief to the listing language.',
        'teaser_title' => 'Sample Swedish inventory',
        'teaser_subtitle' => 'Masked preview of live Sweden listings. Register to see domains and buy.',
        'blog_slugs' => [
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'how-to-choose-a-publisher-site-dr-da-traffic-niche',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'Does Sweden include other Nordic countries?',
                'a' => 'No. Filter Denmark, Norway, or Finland after login — or use those landers.',
            ],
            [
                'q' => 'Is the article in Swedish?',
                'a' => 'Usually yes. Confirm the listing language before you brief.',
            ],
            [
                'q' => 'Are domains public?',
                'a' => 'Not on this page. Register to see hosts.',
            ],
            [
                'q' => 'How is delivery tracked?',
                'a' => 'The live URL is attached to the order for approval or revision.',
            ],
        ],
    ],
    'norway' => [
        'slug' => 'guest-posts-norway',
        'codes' => ['no'],
        'market' => 'Norway',
        'keyword' => 'guest posts norway',
        'kicker' => 'Norwegian publishers',
        'title' => 'Guest posts in Norway',
        'meta_title' => 'Guest Posts in Norway — NO Publishers, EUR',
        'meta_description' => 'Buy guest posts on verified Norwegian publishers. EUR wallet, tracked live URLs, and a public sample of Norway inventory.',
        'subtitle' => 'Primary-Norway publishers. Pay in EUR and keep the live URL on the order.',
        'point_1_title' => 'Norway-primary listings',
        'point_1_body' => 'Teasers are NO-primary sites. Other Nordic markets stay on their own landers.',
        'point_2_title' => 'EUR checkout',
        'point_2_body' => 'Quotes and the wallet are in euro even when the publisher is Norwegian.',
        'point_3_title' => 'How to buy',
        'point_3_body' => 'Register, filter Norway, send the brief in the listing language, and approve the live URL on the order.',
        'teaser_title' => 'Sample Norwegian inventory',
        'teaser_subtitle' => 'Masked preview of live Norway listings. Register to open domains and check out.',
        'blog_slugs' => [
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'how-to-choose-a-publisher-site-dr-da-traffic-niche',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'Is this mixed with Sweden or Denmark?',
                'a' => 'No. This page is primary-Norway only.',
            ],
            [
                'q' => 'Bokmål or Nynorsk?',
                'a' => 'Check the listing language. Most sites use Norwegian Bokmål; match the brief to what the publisher publishes.',
            ],
            [
                'q' => 'Do you show the domain here?',
                'a' => 'No. Hosts stay masked until you register.',
            ],
            [
                'q' => 'How do I buy?',
                'a' => 'Create an account, fund the EUR wallet, filter Norway, and send the brief.',
            ],
        ],
    ],
    'bulgaria' => [
        'slug' => 'guest-posts-bulgaria',
        'codes' => ['bg'],
        'market' => 'Bulgaria',
        'keyword' => 'guest posts bulgaria',
        'kicker' => 'Bulgarian publishers',
        'title' => 'Guest posts in Bulgaria',
        'meta_title' => 'Guest Posts in Bulgaria — BG Publishers, EUR',
        'meta_description' => 'Buy guest posts on verified Bulgarian publishers. EUR wallet, tracked live URLs, and a public sample of Bulgaria inventory.',
        'subtitle' => 'Primary-Bulgaria publishers with a EUR price and a live URL on the order.',
        'point_1_title' => 'Bulgaria-primary listings',
        'point_1_body' => 'This preview is BG-primary sites. Neighbouring markets stay on their own filters after login.',
        'point_2_title' => 'EUR wallet',
        'point_2_body' => 'Checkout is in euro. Fund once and buy Bulgarian placements without a new invoice per site.',
        'point_3_title' => 'Language',
        'point_3_body' => 'Most BG-primary sites publish in Bulgarian. Match the brief to the listing language.',
        'teaser_title' => 'Sample Bulgarian inventory',
        'teaser_subtitle' => 'Masked preview of live Bulgaria listings. Register to see domains and buy.',
        'blog_slugs' => [
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'how-to-choose-a-publisher-site-dr-da-traffic-niche',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'Can I buy Bulgarian guest posts here?',
                'a' => 'Yes. Register, filter country Bulgaria, and check out in EUR.',
            ],
            [
                'q' => 'Is the article in Bulgarian?',
                'a' => 'Usually yes. Confirm the listing language before you write.',
            ],
            [
                'q' => 'Are domains public?',
                'a' => 'Not on this page. Register to see hosts.',
            ],
            [
                'q' => 'How is the live URL delivered?',
                'a' => 'The publisher submits it on the order for review.',
            ],
        ],
    ],
    'hungary' => [
        'slug' => 'guest-posts-hungary',
        'codes' => ['hu'],
        'market' => 'Hungary',
        'keyword' => 'guest posts hungary',
        'kicker' => 'Hungarian publishers',
        'title' => 'Guest posts in Hungary',
        'meta_title' => 'Guest Posts in Hungary — HU Publishers, EUR',
        'meta_description' => 'Buy guest posts on verified Hungarian publishers. EUR wallet, tracked live URLs, and a public sample of Hungary inventory.',
        'subtitle' => 'Primary-Hungary publishers. Pay in EUR and keep the live URL on the order.',
        'point_1_title' => 'Hungary-primary listings',
        'point_1_body' => 'Teasers are HU-primary sites — not a mixed Central Europe dump.',
        'point_2_title' => 'EUR checkout',
        'point_2_body' => 'Quotes and the wallet are in euro. Fund once, then buy Hungarian placements.',
        'point_3_title' => 'How to buy',
        'point_3_body' => 'Register, filter Hungary, send the brief in the listing language, and approve the live URL on the order.',
        'teaser_title' => 'Sample Hungarian inventory',
        'teaser_subtitle' => 'Masked preview of live Hungary listings. Register to open domains and check out.',
        'blog_slugs' => [
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'how-to-choose-a-publisher-site-dr-da-traffic-niche',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'Can I buy Hungarian guest posts here?',
                'a' => 'Yes. Register, filter country Hungary, and check out in EUR.',
            ],
            [
                'q' => 'Should the article be in Hungarian?',
                'a' => 'Most HU-primary sites publish in Hungarian. Match the brief to the listing.',
            ],
            [
                'q' => 'Do you show domains here?',
                'a' => 'No. Hosts stay masked until you register.',
            ],
            [
                'q' => 'How does delivery work?',
                'a' => 'The publisher submits the live URL on the order. You approve it or request changes there.',
            ],
        ],
    ],
    'estonia' => [
        'slug' => 'guest-posts-estonia',
        'codes' => ['ee'],
        'market' => 'Estonia',
        'keyword' => 'guest posts estonia',
        'kicker' => 'Estonian publishers',
        'title' => 'Guest posts in Estonia',
        'meta_title' => 'Guest Posts in Estonia — EE Publishers, EUR',
        'meta_description' => 'Buy guest posts on verified Estonian publishers. EUR wallet, tracked live URLs, and a public sample of Estonia inventory.',
        'subtitle' => 'Primary-Estonia publishers with a EUR price and a live URL on the order.',
        'point_1_title' => 'Estonia-primary listings',
        'point_1_body' => 'This preview is EE-primary sites. Latvia and Lithuania stay on their own filters after login.',
        'point_2_title' => 'EUR wallet',
        'point_2_body' => 'Checkout is in euro. Fund once and buy Estonian placements without a new invoice per site.',
        'point_3_title' => 'Language',
        'point_3_body' => 'Most EE-primary sites publish in Estonian. Match the brief to the listing language.',
        'teaser_title' => 'Sample Estonian inventory',
        'teaser_subtitle' => 'Masked preview of live Estonia listings. Register to see domains and buy.',
        'blog_slugs' => [
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'how-to-choose-a-publisher-site-dr-da-traffic-niche',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'Is this a Baltic bundle?',
                'a' => 'No. This page is primary-Estonia only. Filter Latvia or Lithuania after login if you need those markets.',
            ],
            [
                'q' => 'Is the article in Estonian?',
                'a' => 'Usually yes. Confirm the listing language before you write.',
            ],
            [
                'q' => 'Are domains public?',
                'a' => 'Not on this page. Register to see hosts.',
            ],
            [
                'q' => 'How do I buy?',
                'a' => 'Create an account, fund the EUR wallet, filter Estonia, and send the brief.',
            ],
        ],
    ],
    'poland' => [
        'slug' => 'guest-posts-poland',
        'codes' => ['pl'],
        'market' => 'Poland',
        'keyword' => 'guest posts poland',
        'kicker' => 'Polish publishers',
        'title' => 'Guest posts in Poland',
        'meta_title' => 'Guest Posts in Poland — PL Publishers, EUR',
        'meta_description' => 'Buy guest posts on verified Polish publishers. EUR wallet, tracked live URLs, and a public sample of Poland inventory — not a mixed CEE dump.',
        'subtitle' => 'Primary-Poland publishers with a EUR checkout price and a live URL on the order. Polish is a catalog language and a country filter; they are not the same thing.',
        'point_1_title' => 'Poland-primary listings',
        'point_1_body' => 'This preview is sites whose primary country is Poland. Czechia, Slovakia, and Hungary stay on their own filters after login — this is not a “Central Europe” bundle.',
        'point_2_title' => 'EUR, not PLN checkout',
        'point_2_body' => 'Quotes and the wallet are in euro. Convert once when you fund; order prices stay in EUR even when the publisher is Polish.',
        'point_3_title' => 'Language vs country',
        'point_3_body' => 'Most PL-primary sites publish in Polish. Confirm the listing language before you write the brief. An English-language site hosted in Poland is a different row.',
        'teaser_title' => 'Sample Polish inventory',
        'teaser_subtitle' => 'Masked preview of live Poland listings. Register to see domains and place the order.',
        'blog_slugs' => [
            'buy-guest-posts-in-europe-how-to-choose-publisher-sites',
            'how-to-choose-a-publisher-site-dr-da-traffic-niche',
            'wallet-escrow-and-refunds-explained',
        ],
        'faqs' => [
            [
                'q' => 'Is this a Central / Eastern Europe bundle?',
                'a' => 'No. This page is primary-Poland only. Filter other CEE countries after login if you need those markets.',
            ],
            [
                'q' => 'Will the article be in Polish?',
                'a' => 'Usually yes when the listing language is Polish. Match the brief to the language on the catalog row — country and language are separate filters.',
            ],
            [
                'q' => 'Can I pay in złoty?',
                'a' => 'Checkout is EUR. Convert once when you fund the wallet; placement prices stay in euro.',
            ],
            [
                'q' => 'How do I buy a Polish guest post?',
                'a' => 'Register, fund the EUR wallet, filter Poland, and send the brief. The live URL comes back on the order for review.',
            ],
        ],
    ],
];
